Traceback (most recent call last):
  File "C:\Users\luiss\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\luiss\anaconda3\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\luiss\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\luiss\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\luiss\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\luiss\anaconda3\lib\site-packages\nbclient\client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "C:\Users\luiss\anaconda3\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "C:\Users\luiss\anaconda3\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
Give the logographic value of the following signs
𒌓	UTU		Šamaš		Sun
𒌓	U₄		umu		day
𒌓	BABBAR	peṣû		white
𒆳	KUR		mātu		country	
𒀭	DINGIR	īlu		god
𒄑	GIŠ		(iṣu)		wood
𒀀	A		(mû)		water
𒂍	E₂		bītum		house
𒂗	EN		bēlum		lord
𒃲	gal		rabûm	big

Transliterate the following word:
𒅎	
𒈾
𒀭
𒄑
𒌑
𒀀
𒆷
𒈠
𒀜
𒈝
𒁉𒌅𒌝
𒁁𒇻𒌝
𒊏𒁍𒌝
𒃲


Vocabulary
abum
ālum
amtum
Bēlum
bītum
hurāṣum
ilum
iltum
kaspum
u
mārtum
mārum
qaqqadum
ṣābum
šarratum
šarrum
wardum

Divide the word of the vocabulary into syllables and write them with cuneiform .

------------------

[1;36m  Input [1;32mIn [2][1;36m[0m
[1;33m    Give the logographic value of the following signs[0m
[1;37m         ^[0m
[1;31mSyntaxError[0m[1;31m:[0m invalid syntax

SyntaxError: invalid syntax (<ipython-input-2-850d5acee3c4>, line 1)

